name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: 
    ^2.2.3
  provider: ^6.1.2
  http:  1.2.2
  cached_network_image: 3.3.1
  flutter_cache_manager: ^3.3.3
  intl: 0.19.0
  image_picker: 1.1.2
  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/