name: surf_flutter_summer_school_24
description: "This is an AMAZING program with which you can watch and upload your beautiful photos from YandexDisk  "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: 
    ^2.2.3
  provider: ^6.1.2
  http:  1.2.2
  cached_network_image: 3.3.1
  flutter_cache_manager: ^3.3.3
  intl: 0.19.0
  image_picker: 1.1.2
  dio: ^5.5.0+1
  bloc: 8.1.4
  get: 4.6.6
  flutter_staggered_grid_view: 0.7.0
  flutter_launcher_icons: ^0.13.1
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  android: true
  image_path: "assets/icons/postogramIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/